server.port=8080
spring.application.name=StudentManagement
#spring.data.mongodb.uri=mongodb://student-management-db:27017/studentdb
#spring.data.mongodb.uri=mongodb+srv://stsrin:stsfal@cluster0.ihquj.mongodb.net/studentdb?retryWrites=true&w=majority
spring.data.mongodb.uri=${MONGO_DB_URL}
